In [38]:
import numpy as np


In [39]:
genotype = np.random.randint(100,200,size=50)
genotype

array([123, 131, 140, 149, 159, 172, 169, 175, 142, 132, 145, 184, 152,
       106, 171, 198, 165, 167, 128, 139, 113, 171, 176, 163, 106, 148,
       198, 163, 108, 100, 111, 184, 130, 125, 103, 103, 164, 140, 174,
       168, 160, 107, 104, 199, 195, 107, 103, 129, 141, 157])

In [40]:
change = np.random.randint(50,size=5)
change

array([19, 24,  8, 26, 43])

In [41]:
deltah=-300

In [42]:
[genotype[i] for i in change]

[139, 106, 142, 198, 199]

In [43]:
p = [genotype[i]+deltah if i in change else genotype[i] for i in range(50)]
p

[123,
 131,
 140,
 149,
 159,
 172,
 169,
 175,
 -158,
 132,
 145,
 184,
 152,
 106,
 171,
 198,
 165,
 167,
 128,
 -161,
 113,
 171,
 176,
 163,
 -194,
 148,
 -102,
 163,
 108,
 100,
 111,
 184,
 130,
 125,
 103,
 103,
 164,
 140,
 174,
 168,
 160,
 107,
 104,
 -101,
 195,
 107,
 103,
 129,
 141,
 157]

In [44]:
[p[i] for i in change]

[-161, -194, -158, -102, -101]

In [45]:
print(len([[]]))

1


In [46]:
[0]+[i for i in range(3)]

[0, 0, 1, 2]

In [47]:
k = [i for i in range(5)]
[0]+[i for i in k[1:]]

[0, 1, 2, 3, 4]

In [1]:
import numpy as np
d = 10
gradient_rate = 1
K = np.ceil(gradient_rate* d)
k_d = np.random.choice(10,size=10,replace=False)
k_d

array([2, 8, 0, 9, 5, 4, 6, 3, 1, 7])